# استخدم صورة Python الرسمية
FROM python:3.12-slim

# تعيين مجلد العمل داخل الحاوية
WORKDIR /app

# نسخ ملفات المشروع
COPY . /app

# تثبيت التبعيات
RUN pip install --no-cache-dir -r requirements.txt

# تعيين أمر التشغيل الافتراضي
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
